id: P000398
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19227
  title: དགག་ལན་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    b8473868a94741bfb0f08ea6b1771def:
      image_group_id: I4981
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
